-- create or replace function get_company_admins(company_id uuid) returns setof uuid as $$
--   select staff_id from company_staff where company_id = $1
--   and (role = 'admin' or role = 'super_admin')
-- $$ stable language sql security definer;